import { Strain, GrowthStageInfo } from '../types';

export const DEFAULT_STRAINS: Strain[] = [
  {
    id: 'sunset-sherbert',
    name: 'Sunset Sherbert',
    tag: 'Indica-Dominant · Cold Cured',
    desc: 'Dense, royal purple and deep violet calyxes blanketed in crystalline milky resin trichomes, accented by vibrant curly copper-orange pistils and sweet dessert terpenes.',
    img: '/sunset-sherbert.jpg',
    cbdPercent: 18.8,
    thcPercent: 0.14,
    terpenes: [
      { name: 'beta-Caryophyllene', percentage: 1.15, note: 'Warm spice, black pepper, deep somatic calm' },
      { name: 'Myrcene', percentage: 0.88, note: 'Sweet herbal earth, muscular release' },
      { name: 'Limonene', percentage: 0.52, note: 'Meyer lemon zest, gentle headspace clarity' },
    ],
    aromaNotes: 'Candied citrus peel, sweet loam, and lavender undertones.',
    lineage: 'Sherbet phenotype clone',
    phenotypeAppearance: 'Rich royal purple calyx clusters encrusted with frosty white diamond trichomes and twisting amber-orange stigmas.',
    floweringWeeks: 8,
    harvestWindow: 'October Week 1',
  },
  {
    id: 'northern-lights',
    name: 'Northern Lights',
    tag: 'Indica · Heirloom Clone',
    desc: 'Dense, frosty hand-trimmed buds featuring forest greens and delicate lavender hues, blanketed in crystalline milky resin heads.',
    img: 'https://images.unsplash.com/photo-1603909223429-69bb7101f420?auto=format&fit=crop&w=800&q=80',
    cbdPercent: 19.4,
    thcPercent: 0.16,
    terpenes: [
      { name: 'alpha-Pinene', percentage: 1.25, note: 'Crisp pine forest, alert breathing, mental calm' },
      { name: 'Myrcene', percentage: 0.95, note: 'Earthy, sedative easing' },
      { name: 'Humulene', percentage: 0.45, note: 'Subtle herbal hops, grounding aroma' },
    ],
    aromaNotes: 'Sierra pine, damp peat moss, and spiced sandalwood.',
    lineage: 'NL #5 heritage clone',
    phenotypeAppearance: 'Tight green bract clusters with light purple sugar leaf accents and heavy resin sheen.',
    floweringWeeks: 8.5,
    harvestWindow: 'Late September',
  },
  {
    id: 'harlequin',
    name: 'Harlequin',
    tag: 'Sativa-Dominant · Select Phenotype',
    desc: 'Iconic sativa-dominant floral spear with frosty crystalline sugar leaves and stacked calyxes blanketed in glistening glandular trichomes, accented by delicate golden-amber stigmas.',
    img: '/harlequin.jpg',
    cbdPercent: 17.6,
    thcPercent: 0.12,
    terpenes: [
      { name: 'Terpinolene', percentage: 0.92, note: 'Wildflowers, fresh pine, uplifting mood' },
      { name: 'Ocimene', percentage: 0.68, note: 'Sweet floral citrus, daytime freshness' },
      { name: 'beta-Caryophyllene', percentage: 0.55, note: 'Warm spice, stress relief' },
    ],
    aromaNotes: 'Crushed mango, roasted hazelnuts, and spring pine needles.',
    lineage: 'Colombian Gold clone',
    phenotypeAppearance: 'Towering conical floral spear heavily encrusted in crystalline trichomes with vibrant botanical green calyxes and frosty serrated sugar leaves.',
    floweringWeeks: 9,
    harvestWindow: 'Mid October',
  },
  {
    id: 'sour-space-candy',
    name: 'Sour Space Candy',
    tag: 'Hybrid · Living Soil Clone',
    desc: 'Exquisite seedless buds boasting vivid deep violet calyxes blanketed in frosty crystalline trichomes, accented with twisting copper-orange stigmas and pungent candied diesel terpenes.',
    img: '/sour-space-candy.jpg',
    cbdPercent: 20.2,
    thcPercent: 0.18,
    terpenes: [
      { name: 'Myrcene', percentage: 1.35, note: 'Potent soothing physical relief' },
      { name: 'Terpinolene', percentage: 0.75, note: 'Crisp fruity tartness' },
      { name: 'Pinene', percentage: 0.48, note: 'Bright woodland clarity' },
    ],
    aromaNotes: 'Sour green apple, pungent diesel fuel, and candied cherry peel.',
    lineage: 'Sour Tsunami clone cutting',
    phenotypeAppearance: 'Dense conical nugs with deep purple calyx clusters encrusted with frosty white diamond trichomes and amber-orange pistils.',
    floweringWeeks: 8,
    harvestWindow: 'Early October',
  },
  {
    id: 'cupcake',
    name: 'Cupcake',
    tag: 'Hybrid · Dessert Cure',
    desc: 'Frosty conical nugs with bright orange pistils and sweet dessert terpenes.',
    img: '/cupcake.jpg',
    cbdPercent: 18.2,
    thcPercent: 0.16,
    terpenes: [
      { name: 'Limonene', percentage: 1.12, note: 'Sweet citrus dessert brightness' },
      { name: 'Myrcene', percentage: 0.84, note: 'Soft herbal calm' },
      { name: 'beta-Caryophyllene', percentage: 0.52, note: 'Warm spice finish' },
    ],
    aromaNotes: 'Vanilla frosting, orange zest, and creamy dessert pastry.',
    lineage: 'Cupcake phenotype clone',
    phenotypeAppearance: 'Frosty conical nug with vivid orange pistils and dense milky trichomes.',
    floweringWeeks: 8,
    harvestWindow: 'Early October',
  },
  {
    id: 'cakeboss',
    name: 'CakeBoss',
    tag: 'Hybrid · Frosted Cake',
    desc: 'Pale-green frosty nugs with sparse amber pistils and a softly sweet cake aroma.',
    img: '/cakeboss.jpg',
    cbdPercent: 18.4,
    thcPercent: 0.15,
    terpenes: [
      { name: 'Limonene', percentage: 1.08, note: 'Bright lemon cake sweetness' },
      { name: 'Myrcene', percentage: 0.86, note: 'Gentle earthy ease' },
      { name: 'Linalool', percentage: 0.48, note: 'Soft floral cream' },
    ],
    aromaNotes: 'Pale vanilla cake, lemon cream, and light earth.',
    lineage: 'CakeBoss select phenotype',
    phenotypeAppearance: 'Pale-green frosty nug with compact bracts and sparse amber pistils.',
    floweringWeeks: 8,
    harvestWindow: 'Early October',
  },
  {
    id: 'gelatti',
    name: 'Gelatti',
    tag: 'Hybrid · Gelato Cross',
    desc: 'Purple and green frosty nugs with curling orange pistils and rich dessert-gas terpenes.',
    img: '/gelatti.jpg',
    cbdPercent: 18.1,
    thcPercent: 0.17,
    terpenes: [
      { name: 'Limonene', percentage: 1.18, note: 'Citrus gelato lift' },
      { name: 'beta-Caryophyllene', percentage: 0.92, note: 'Peppery gas depth' },
      { name: 'Myrcene', percentage: 0.72, note: 'Sweet earthy body' },
    ],
    aromaNotes: 'Gelato cream, grape candy, and pungent dessert gas.',
    lineage: 'Gelato cross selection',
    phenotypeAppearance: 'Purple and green frosty nugs stacked with orange pistils and heavy resin.',
    floweringWeeks: 8.5,
    harvestWindow: 'Mid October',
  },
];

export const GROWTH_STAGES: GrowthStageInfo[] = [
  {
    key: 'clone_cutting',
    progressRange: [0, 0.20],
    label: 'Stage I: Clone Cutting',
    subLabel: 'Living Soil Strike · Day 1 – 7',
    timeframe: 'Day 1 – 7',
    title: '45° Nursery Clone Cutting',
    description: 'Fresh 45-degree angle nursery cutting anchored in living organic soil. Trimmed fan leaf tips minimize transpiration while vascular callus forms at the cut base.',
    botanicalHighlight: 'Callus tissue initiates adventitious rooting as the vascular cambium responds to living soil mycorrhizae.',
    cannabinoids: {
      cbd: '< 0.5%',
      thc: '< 0.05%',
      terpenes: '0.1% foliage',
    },
    keyFeatures: ['45° angle nursery cut base', 'Trimmed fan leaf tips', 'Living organic soil contact'],
  },
  {
    key: 'rooting',
    progressRange: [0.20, 0.40],
    label: 'Stage II: Rooting & Apical Shoot',
    subLabel: 'Root Establishment · Day 8 – 16',
    timeframe: 'Day 8 – 16',
    title: 'Adventitious Roots & Shoot Vigor',
    description: 'White adventitious root tendrils branch deep into the living mycorrhizal soil. The apical center shoot stretches upward, unfolding fresh true palmate leaves.',
    botanicalHighlight: 'Adventitious root hairs interface with soil fungal networks, supercharging nutrient and water uptake.',
    cannabinoids: {
      cbd: '1.2%',
      thc: '0.06%',
      terpenes: '0.3% terpenes',
    },
    keyFeatures: ['Branching white adventitious roots', 'Microscopic root hairs', 'Apical shoot takeoff'],
  },
  {
    key: 'vegetative',
    progressRange: [0.40, 0.65],
    label: 'Stage III: Vegetative Growth',
    subLabel: 'Canopy Formation · Weeks 3 – 7',
    timeframe: 'Weeks 3 – 7',
    title: 'Lush Palmate Foliage',
    description: 'Fibrous stalks develop sturdy nodes with iconic 5, 7, and 9-bladed serrated fan leaves absorbing warm studio light.',
    botanicalHighlight: 'Robust xylem and phloem transport silica and minerals, building sturdy structural branches.',
    cannabinoids: {
      cbd: '2.5%',
      thc: '0.08%',
      terpenes: '0.5% monoterpenes',
    },
    keyFeatures: ['Multi-bladed serrated fan leaves', 'Alternating robust nodes', 'Vigorous sun-seeking canopy'],
  },
  {
    key: 'early_bloom',
    progressRange: [0.65, 0.82],
    label: 'Stage IV: Early Flower',
    subLabel: 'Calyx Development · Weeks 8 – 10',
    timeframe: 'Weeks 8 – 10',
    title: 'Calyx Swell & Fresh Stigmas',
    description: 'Female pre-flowers swell along the nodes. Delicate paired stigmas (pistils) push outward from green calyxes with early hints of light purple bract margins.',
    botanicalHighlight: 'Capitate-stalked glandular trichomes begin crystal formation across calyxes and sugar leaves.',
    cannabinoids: {
      cbd: '8.5%',
      thc: '0.10%',
      terpenes: '1.4% fresh aromatics',
    },
    keyFeatures: ['Swelling teardrop calyxes', 'Twin protruding white stigmas', 'Initial crystal resin beading'],
  },
  {
    key: 'cured_nug',
    progressRange: [0.82, 1.0],
    label: 'Stage V: Seedless Cured Flower',
    subLabel: 'Final Flower · Green & Light Purple',
    timeframe: 'Artisanal Cure',
    title: 'Seedless Flower in Green & Light Purple',
    description: 'Hand-trimmed, seedless cured flower. Showcases vibrant botanical green bracts crowned with soft light purple and lilac hues, curly fiery copper pistils, and frosty crystalline trichomes.',
    botanicalHighlight: '100% seedless female flower. Anthocyanin synthesis produces soft light purple calyx margins alongside emerald green chlorophyll.',
    cannabinoids: {
      cbd: '18.8% – 20.4%',
      thc: '< 0.20%',
      terpenes: '2.85% Total Terpenes',
    },
    keyFeatures: ['Botanical green & soft light purple calyxes', 'Completely seedless sinsemilla', 'Frosty blanket of milky/amber trichomes'],
  },
];

export function getStageForProgress(progress: number): GrowthStageInfo {
  const clamped = Math.max(0, Math.min(1, progress));
  const stage = GROWTH_STAGES.find((s) => clamped >= s.progressRange[0] && clamped <= s.progressRange[1]);
  return stage || GROWTH_STAGES[GROWTH_STAGES.length - 1];
}
